import React from 'react'
import { Link, graphql } from 'gatsby'

import BlogBio from '../components/BlogBio'
import ExternalLink from '../components/ExternalLink'
import Layout from '../components/Layout'
import SEO from '../components/Seo'
import { rhythm, scale } from '../utils/typography'

import './BlogPost.css'

// FIXME: these should really be auto generated by Gatsby tooling
type Props = {
  data: {
    markdownRemark: {
      excerpt: string
      html: string
      timeToRead: string // FIXME: use
      frontmatter: {
        description: string
        date: string
        title: string
        featuredImage?: {
          childImageSharp: {
            fixed: {
              src: string
            }
          }
        }
      }
    }
    site: {
      siteMetadata: {
        siteUrl: string
      }
    }
  }
  location: Location
  pageContext: any
}

export default function BlogPostTemplate({ data, location, pageContext }: Props) {
  const post = data.markdownRemark
  const { previous, next, slug } = pageContext
  const { siteUrl } = data.site.siteMetadata
  const featuredImageSrc = post.frontmatter.featuredImage
    ? `${siteUrl}${post.frontmatter.featuredImage.childImageSharp.fixed.src}`
    : undefined

  const discussUrl = `https://mobile.twitter.com/search?q=${encodeURIComponent(
    `https://skovhus.github.io${slug}`
  )}`

  return (
    <Layout location={location}>
      <SEO
        description={post.frontmatter.description || post.excerpt}
        image={featuredImageSrc}
        location={location}
        pageTitle={post.frontmatter.title}
      />

      <article>
        <h1>{post.frontmatter.title}</h1>
        <p
          style={{
            ...scale(-1 / 5),
            display: `block`,
            marginBottom: rhythm(1),
            marginTop: rhythm(-1),
          }}
        >
          {post.frontmatter.date} • {post.timeToRead} minute read
        </p>
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
        <ExternalLink linkTo={discussUrl}>Discuss this post on Twitter.</ExternalLink>
        <hr
          style={{
            marginBottom: rhythm(1),
            marginTop: rhythm(1),
          }}
        />
      </article>

      <BlogBio />

      <ul
        style={{
          display: `flex`,
          flexWrap: `wrap`,
          justifyContent: `space-between`,
          listStyle: `none`,
          padding: 0,
        }}
      >
        <li>
          {previous && (
            <Link to={previous.fields.slug} rel="prev">
              ← {previous.frontmatter.title}
            </Link>
          )}
        </li>
        <li>
          {next && (
            <Link to={next.fields.slug} rel="next">
              {next.frontmatter.title} →
            </Link>
          )}
        </li>
      </ul>
    </Layout>
  )
}

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      excerpt(pruneLength: 200)
      html
      timeToRead
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        description
        featuredImage {
          childImageSharp {
            fixed(width: 500, height: 500) {
              ...GatsbyImageSharpFixed
            }
          }
        }
      }
    }

    site {
      siteMetadata {
        siteUrl
      }
    }
  }
`
